name: wdapp
description: "Prototype WingDing Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  async: ^2.13.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  freezed: ^3.2.4
  go_router: ^17.0.1
  jwt_decoder: ^2.0.1
  provider: ^6.1.5+1
  result_dart: ^2.1.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loc.json
    - assets/locidx.json